### ISSUE TITLE
ROS2 support

### ISSUE THREAD

**Issue by fmros** [CumaOzavci/nav_rest_api#1]
Hy,

it would be nice to have a ROS2 support for this package.

**Comment by CumaOzavci** [comment]
@fmros, i wrote this package to help people who started writing their own robotics API. I could not find good practical examples while searching for my project so i created one.

This was 2 years ago. 

ROS community created much more capable open source projects ([Open-RMF](https://github.com/open-rmf/rmf) etc.) during this time. I strongly suggest you to take a look at them. 

Hereby, i don't see a reason for ROS2 support.
